Moved tooling folder to submodule
CommunityToolkit/Labs-Windows pull request #409
Opened 2023-03-15 19:15 UTC by Arlodotexe

## Overview
This PR removes the contents of `./tooling`, and re-adds it via our new [tooling repo](https://github.com/CommunityToolkit/Tooling-Windows-Submodule).

Users will need to use `git pull --recurse-submodules` instead of just `git pull` to bring the submodule into the local working tree.

2023-03-15 19:24 UTC, michael-hawker requested changes

2023-03-15 19:24 UTC, michael-hawker commented on .github/workflows/build.yml
> +          submodules: recursive
That's nice and simple 🙂

2023-03-15 19:24 UTC, michael-hawker commented on .github/workflows/build.yml
Remove the `new-experiment` and `project-template` jobs as those run out of the Tooling repo now, we don't need to do that all the time here anymore, just the main component build.

`wasm-linux` **can stay** as that includes the components and is super quick anyway.

2023-03-15 19:24 UTC, michael-hawker commented on .gitmodules
Add a comment near the top of the root readme about how to properly check this repo out like you did in the PR comment about the git pull with the recurse parameter.

2023-03-15 19:24 UTC, Arlodotexe commented on .github/workflows/build.yml
Good call, will do

2023-03-15 19:28 UTC, michael-hawker commented on .github/workflows/build.yml
Edited comment, forgot I split that as two jobs in the new place for the template build itself and the new experiment creation, in either case, we're all set here to minimize duplicated effort, yay! 🎉🎉🎉

Thanks for the quick turnaround.

2023-03-15 19:39 UTC, michael-hawker commented on .github/workflows/build.yml
Ah, remembered that `labexp` template name is now `ctk-component`. Should be fine here now that we removed the `new-experiment` job, but not sure if we call that out in the readme anywhere as well?

2023-03-15 19:41 UTC, michael-hawker approved these changes

2023-03-15 20:49 UTC, michael-hawker commented
Updated branch protections to not wait on the `new-experiment` step that doesn't exist.

WinUI 2 build failed due to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/9

2023-03-15 21:37 UTC, michael-hawker commented
Huh, build failed but I couldn't get logs from it... assume same issue? Re-running... 😟

2023-03-22 05:40 UTC, michael-hawker commented
Thought we disabled the SG tests here?

```
  Failed PaneOption_GeneratesTitleProperty [718 ms]
  Error Message:
   Test method CommunityToolkit.Tooling.SampleGen.Tests.ToolkitSampleMetadataTests.PaneOption_GeneratesTitleProperty threw exception: 
System.InvalidOperationException: Sequence contains no matching element
  Stack Trace:
      at System.Linq.ThrowHelper.ThrowNoMatchException()
   at CommunityToolkit.Tooling.SampleGen.Tests.ToolkitSampleMetadataTests.VerifyGenerateSources(String assemblyName, String source, IIncrementalGenerator[] generators, Boolean ignoreDiagnostics, ValueTuple`2[] results) in /_/CommunityToolkit.Tooling.SampleGen.Tests/ToolkitSampleMetadataTests.cs:line 533
   at CommunityToolkit.Tooling.SampleGen.Tests.ToolkitSampleMetadataTests.PaneOption_GeneratesTitleProperty() in /_/CommunityToolkit.Tooling.SampleGen.Tests/ToolkitSampleMetadataTests.cs:line 91
```

They're run in the tooling repo now, so we shouldn't have to run these tests here too.

2023-03-22 17:09 UTC, merged