Upgrade to .NET 7, enable WASM optimizations
CommunityToolkit/Labs-Windows pull request #485
Opened 2023-08-02 21:32 UTC by Arlodotexe

Companion PR to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/117, which should be closed before merging this.

As noted:
> Any codebase consuming the tooling repo will need to be adjusted to account for the new nullable annotations and analyzers added between netstandard2.0 and net7.0.

This PR pulls in the .NET 7 upgrade and fixes the new warnings and errors that appeared in our codebase as a result.

2023-08-18 20:11 UTC, michael-hawker requested changes
Looks good, few things to tweak. Still a low-priority for this though with the focus on the main release.

We should link a tracking issue for the investigation on the fixed .NET 7 version from the tooling repo.

2023-08-18 20:11 UTC, michael-hawker commented on .editorconfig
> +# Labs only: XML comment has param tag but no paramater by that name.
Isn't this a bug then on the comment that can be fixed?

2023-08-18 20:11 UTC, michael-hawker commented on .editorconfig
> +dotnet_diagnostic.CA1001.severity = none
Should have a comment here labeling what this is, it's helpful. 🙂

2023-08-18 20:11 UTC, michael-hawker commented on .github/workflows/build.yml
Should diff and pull-over other updates to the build.yml, like pushing to the PR feed and such.

2023-08-18 20:11 UTC, michael-hawker commented on components/DataTable/samples/DataTable.Samples.csproj
Why is this deleted?

2023-08-18 20:11 UTC, michael-hawker commented on components/DataTable/src/MultiTarget.props
Why is this deleted? Or did Uno add support for the ItemsPresenter Header/Footer?

2023-08-18 20:11 UTC, michael-hawker commented on components/StackedNotificationsBehavior/src/Notification.cs
We can delete this whole component as it was migrated to the main repo. Is Segmented still here too, as we migrated that one too, right? Feel free to do a quick compare and pass and clean-up anything no longer needed here.

2023-08-18 21:28 UTC, Arlodotexe commented on components/DataTable/samples/DataTable.Samples.csproj
Good question, that shouldn't have happened. I'll restore it.

2023-08-18 21:34 UTC, Arlodotexe commented on components/StackedNotificationsBehavior/src/Notification.cs
Good catch, filed a ticket here -> https://github.com/CommunityToolkit/Labs-Windows/issues/489

2023-09-28 16:22 UTC, Arlodotexe commented on components/DataTable/src/MultiTarget.props
This shouldn't have happened. I'll need to restore these.

2023-10-03 15:09 UTC, Arlodotexe commented on .editorconfig
> +dotnet_diagnostic.CA2213.severity = none
```suggestion
# Todo: Clean up suppression of CA1063 and implement IDisposable correctly
# https://github.com/CommunityToolkit/Labs-Windows/issues/443
dotnet_diagnostic.CA2213.severity = none
```

2023-10-05 07:13 UTC, michael-hawker commented on .github/workflows/build.yml
> +          dotnet nuget push "**/*.nupkg" --api-key dummy --source PullRequests --skip-duplicate
If it's not a PR, then we still need to push to the LabsFeed, as there's no other steps like in the main build that will push to the feed, right?

2023-10-05 07:14 UTC, michael-hawker commented on .github/workflows/build.yml
> +          echo "VERSION_PROPERTY=$($matches['prerelease'])" >> $env:GITHUB_ENV
Since this will always be false, do we just want to exclude it?

2023-10-12 16:16 UTC, michael-hawker commented
@Arlodotexe can you see if any of the open PRs need updating from this? Thanks!

2023-10-17 16:41 UTC, michael-hawker commented
Wasn't sure why GitHub wasn't reporting anything, had to dig-in to the Actions page for the last build and see the 'Startup Failure' seems like one of the actions isn't on the allowlist, going to fix that.

2023-10-17 16:42 UTC, michael-hawker commented
Going to close and re-open to kick off CI again

2023-10-18 01:07 UTC, michael-hawker commented
@Arlodotexe CI is running again, but something up with the call to the pack script:

```
   2 |  ./PackEachExperiment.ps1 -extraBuildProperties "pull-485.1577"
     |                           ~~~~~~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'extraBuildProperties'.
```

Maybe the sub-module isn't updated or something? Should hopefully be an easy fix of some sort either way.

2023-10-22 12:48 UTC, Jay-o-Way commented
Hey guys, check out the MS video: "Upgrade your .NET projects with Visual Studio"
https://build.microsoft.com/en-US/sessions/c5bf6653-f0de-4091-a139-caf7904300c6

2023-10-24 20:48 UTC, merged

2023-10-26 16:15 UTC, michael-hawker commented on .github/workflows/build.yml
> -        run: dotnet nuget update source LabsFeed --username dummy --password ${{ secrets.DEVOPS_PACKAGE_PUSH_TOKEN }}
@Arlodotexe this is still needed in between the added PR step and the 'Push packages' still. This is why `main` is failing, as the source isn't updated to include the token.